-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.Template (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT Template_pkey PRIMARY KEY (user_id),
  CONSTRAINT Template_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.form_business_idea(project_id),
  CONSTRAINT Template_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.business_model (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  partenaires_cles text,
  activites_cles text,
  proposition_valeur text,
  ressources_humaines text,
  ressources_financieres text,
  ressources_materielles text,
  ressources_intellectuelles text,
  relations_clients text,
  canaux text,
  segments_clients text,
  structure_couts_analyse text,
  structure_couts_liste_des_couts text,
  flux_revenus_analyse text,
  flux_revenus_liste_des_revenus text,
  CONSTRAINT business_model_pkey PRIMARY KEY (project_id),
  CONSTRAINT business_model_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT business_model_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.form_business_idea(project_id)
);
CREATE TABLE public.concurrence (
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  free_direct_definition text NOT NULL,
  free_direct_importance text,
  free_indirect_definition text,
  free_indirect_importance text,
  free_potentiel_definition text,
  free_potentiel_importance text,
  free_segmentation_concurrentielle text,
  free_critere_differentiation_1 text,
  free_critere_differentiation_2 text,
  free_critere_differentiation_3 text,
  concurrent_1_nom text,
  concurrent_1_description text,
  concurrent_1_url text,
  concurrent_1_forces text,
  concurrent_1_faiblesses text,
  concurrent_1_caracteristiques text,
  concurrent_2_nom text,
  concurrent_2_description text,
  concurrent_2_url text,
  concurrent_2_forces text,
  concurrent_2_faiblesses text,
  concurrent_2_caracteristiques text,
  concurrent_3_nom text,
  concurrent_3_description text,
  concurrent_3_url text,
  concurrent_3_forces text,
  concurrent_3_faiblesses text,
  concurrent_3_caracteristiques text,
  concurrent_4_nom text,
  concurrent_4_description text,
  concurrent_4_url text,
  concurrent_4_forces text,
  concurrent_4_faiblesses text,
  concurrent_4_caracteristiques text,
  concurrent_5_nom text,
  concurrent_5_description text,
  concurrent_5_url text,
  concurrent_5_forces text,
  concurrent_5_faiblesses text,
  concurrent_5_caracteristiques text,
  concurrent_6_nom text,
  concurrent_6_description text,
  concurrent_6_url text,
  concurrent_6_forces text,
  concurrent_6_faiblesses text,
  concurrent_6_caracteristiques text,
  concurrent_7_nom text,
  concurrent_7_description text,
  concurrent_7_url text,
  concurrent_7_forces text,
  concurrent_7_faiblesses text,
  concurrent_7_caracteristiques text,
  concurrent_8_nom text,
  concurrent_8_description text,
  concurrent_8_url text,
  concurrent_8_forces text,
  concurrent_8_faiblesses text,
  concurrent_8_caracteristiques text,
  concurrent_9_nom text,
  concurrent_9_description text,
  concurrent_9_url text,
  concurrent_9_forces text,
  concurrent_9_faiblesses text,
  concurrent_9_caracteristiques text,
  concurrent_10_nom text,
  concurrent_10_description text,
  concurrent_10_url text,
  concurrent_10_forces text,
  concurrent_10_faiblesses text,
  concurrent_10_caracteristiques text,
  avis text,
  recommandations text,
  justification_avis text,
  CONSTRAINT concurrence_pkey PRIMARY KEY (project_id),
  CONSTRAINT concurrence_project_id_fkey1 FOREIGN KEY (project_id) REFERENCES public.form_business_idea(project_id),
  CONSTRAINT concurrence_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.conversation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  title text NOT NULL DEFAULT 'Nouvelle conversation'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT conversation_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT conversation_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.form_business_idea (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  nom_projet text,
  produit_service text,
  reponse_besoin text,
  clients_type text,
  moyens_minimum text,
  type_projet text,
  localisation text,
  project_sentence text,
  other_infos text,
  motivations_entrepreneur text,
  equipe_fondatrice text,
  CONSTRAINT form_business_idea_pkey PRIMARY KEY (project_id),
  CONSTRAINT form_business_idea_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.marche (
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  free_marche text,
  free_marches_annexe text,
  free_description_du_marche text,
  free_3_enjeux_principaux text,
  free_evolution_du_marche text,
  free_predictions text,
  free_difficulte_a_l_entree text,
  free_details_difficulte_a_l_entree text,
  free_classification text,
  free_justification_concise text,
  free_marche_viable text,
  pay_economique_opportunite_1_description text,
  pay_economique_opportunite_1_source text,
  pay_economique_opportunite_1_url text,
  pay_economique_opportunite_1_impact_potentiel text,
  pay_economique_opportunite_2_description text,
  pay_economique_opportunite_2_source text,
  pay_economique_opportunite_2_url text,
  pay_economique_opportunite_2_impact_potentiel text,
  pay_economique_opportunite_3_description text,
  pay_economique_opportunite_3_source text,
  pay_economique_opportunite_3_url text,
  pay_economique_opportunite_3_impact_potentiel text,
  pay_economique_menace_1_description text,
  pay_economique_menace_1_source text,
  pay_economique_menace_1_url text,
  pay_economique_menace_1_impact_potentiel text,
  pay_economique_menace_2_description text,
  pay_economique_menace_2_source text,
  pay_economique_menace_2_url text,
  pay_economique_menace_2_impact_potentiel text,
  pay_economique_menace_3_description text,
  pay_economique_menace_3_source text,
  pay_economique_menace_3_url text,
  pay_economique_menace_3_impact_potentiel text,
  pay_sociodemographique_opportunite_1_description text,
  pay_sociodemographique_opportunite_1_source text,
  pay_sociodemographique_opportunite_1_url text,
  pay_sociodemographique_opportunite_1_impact_potentiel text,
  pay_sociodemographique_opportunite_2_description text,
  pay_sociodemographique_opportunite_2_source text,
  pay_sociodemographique_opportunite_2_url text,
  pay_sociodemographique_opportunite_2_impact_potentiel text,
  pay_sociodemographique_opportunite_3_description text,
  pay_sociodemographique_opportunite_3_source text,
  pay_sociodemographique_opportunite_3_url text,
  pay_sociodemographique_opportunite_3_impact_potentiel text,
  pay_sociodemographique_menace_1_description text,
  pay_sociodemographique_menace_1_source text,
  pay_sociodemographique_menace_1_url text,
  pay_sociodemographique_menace_1_impact_potentiel text,
  pay_sociodemographique_menace_2_description text,
  pay_sociodemographique_menace_2_source text,
  pay_sociodemographique_menace_2_url text,
  pay_sociodemographique_menace_2_impact_potentiel text,
  pay_sociodemographique_menace_3_description text,
  pay_sociodemographique_menace_3_source text,
  pay_sociodemographique_menace_3_url text,
  pay_sociodemographique_menace_3_impact_potentiel text,
  pay_technologique_opportunite_1_description text,
  pay_technologique_opportunite_1_source text,
  pay_technologique_opportunite_1_url text,
  pay_technologique_opportunite_1_impact_potentiel text,
  pay_technologique_opportunite_2_description text,
  pay_technologique_opportunite_2_source text,
  pay_technologique_opportunite_2_url text,
  pay_technologique_opportunite_2_impact_potentiel text,
  pay_technologique_opportunite_3_description text,
  pay_technologique_opportunite_3_source text,
  pay_technologique_opportunite_3_url text,
  pay_technologique_opportunite_3_impact_potentiel text,
  pay_technologique_menace_1_description text,
  pay_technologique_menace_1_source text,
  pay_technologique_menace_1_url text,
  pay_technologique_menace_1_impact_potentiel text,
  pay_technologique_menace_2_description text,
  pay_technologique_menace_2_source text,
  pay_technologique_menace_2_url text,
  pay_technologique_menace_2_impact_potentiel text,
  pay_technologique_menace_3_description text,
  pay_technologique_menace_3_source text,
  pay_technologique_menace_3_url text,
  pay_technologique_menace_3_impact_potentiel text,
  pay_exploitation_opportunite_1_recommandation text,
  pay_exploitation_opportunite_1_opportunite_associee text,
  pay_exploitation_opportunite_1_priorite text,
  pay_exploitation_opportunite_2_recommandation text,
  pay_exploitation_opportunite_2_opportunite_associee text,
  pay_exploitation_opportunite_2_priorite text,
  pay_exploitation_opportunite_3_recommandation text,
  pay_exploitation_opportunite_3_opportunite_associee text,
  pay_exploitation_opportunite_3_priorite text,
  pay_attenuation_menace_1_recommandation text,
  pay_attenuation_menace_1_menace_associee text,
  pay_attenuation_menace_1_priorite text,
  pay_attenuation_menace_2_recommandation text,
  pay_attenuation_menace_2_menace_associee text,
  pay_attenuation_menace_2_priorite text,
  pay_attenuation_menace_3_recommandation text,
  pay_attenuation_menace_3_menace_associee text,
  pay_attenuation_menace_3_priorite text,
  pay_vue_d_ensemble text,
  pay_synthese_demande text,
  pay_segment_1_nom text,
  pay_segment_1_ca_potentiel text,
  pay_segment_1_taille_volume text,
  pay_segment_1_caracteristiques text,
  pay_segment_1_frequence_achat text,
  pay_segment_1_panier_moyen text,
  pay_ca_an_un text,
  pay_ca_an_deux text,
  pay_ca_an_trois text,
  pay_justification_projections text,
  pay_facteurs_influence text,
  pay_segment_2_nom text,
  pay_segment_2_ca_potentiel text,
  pay_segment_2_taille_volume text,
  pay_segment_2_caracteristiques text,
  pay_segment_2_frequence_achat text,
  pay_segment_2_panier_moyen text,
  pay_segment_3_nom text,
  pay_segment_3_ca_potentiel text,
  pay_segment_3_taille_volume text,
  pay_segment_3_caracteristiques text,
  pay_segment_3_frequence_achat text,
  pay_segment_3_panier_moyen text,
  avis text,
  justification_avis text,
  CONSTRAINT marche_pkey PRIMARY KEY (project_id),
  CONSTRAINT marche_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT marche_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender text NOT NULL CHECK (sender = ANY (ARRAY['user'::text, 'bot'::text])),
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversation(id)
);
CREATE TABLE public.mini_swot (
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  project_id uuid NOT NULL,
  economique_opportunite_1 text,
  economique_opportunite_2 text,
  economique_menace_1 text,
  economique_menace_2 text,
  socio_opportunite_1 text,
  socio_opportunite_2 text,
  socio_menace_1 text,
  socio_menace_2 text,
  force_1 text,
  force_2 text,
  force_3 text,
  force_4 text,
  faiblesse_1 text,
  faiblesse_2 text,
  faiblesse_3 text,
  faiblesse_4 text,
  recommandations text,
  avis text,
  justification_avis text,
  CONSTRAINT mini_swot_pkey PRIMARY KEY (project_id),
  CONSTRAINT mini_swot_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT mini_swot_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.organisms (
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  organism_segments_principaux text,
  organism_caracteristiques_distinctives text,
  organism_taille_accessibilite text,
  organism_hierarchisation_potentiel text,
  organism_profils_demographiques text,
  organism_traits_psychographiques text,
  organism_comportements_achat text,
  organism_facteurs_influence text,
  organism_etapes_decisionnelles text,
  organism_points_contact_critiques text,
  organism_facteurs_conversion_friction text,
  organism_influences_externes text,
  organism_besoins_explicites text,
  organism_besoins_implicites text,
  organism_motivations_profondes text,
  organism_declencheurs_achat text,
  organism_personas_detailles text,
  organism_facteurs_decisionnels_cles text,
  organism_strategies_engagement text,
  organism_recommandations_marketing text,
  CONSTRAINT organisms_pkey PRIMARY KEY (project_id),
  CONSTRAINT organisms_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.persona_express_b2b (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  identite_professionnelle text,
  contexte_organisationnel text,
  responsabilites_cles text,
  enjeux_business text,
  processus_decision text,
  recherche_information text,
  objections_courantes text,
  strategie_approche text,
  recommandations_b2b text,
  CONSTRAINT persona_express_b2b_pkey PRIMARY KEY (project_id),
  CONSTRAINT persona_express_b2b_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT buyer_b2b_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.persona_express_b2c (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  identite text,
  contexte_personnel text,
  motivations_valeurs text,
  defis_frustrations text,
  comportement_achat text,
  presence_digitale text,
  strategies_marketing text,
  approche_vente text,
  avis text,
  recommandations text,
  justification_avis text,
  recommandations_b2c text,
  CONSTRAINT persona_express_b2c_pkey PRIMARY KEY (project_id),
  CONSTRAINT persona_express_b2c_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT buyer_b2c_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.persona_express_organismes (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  identite_institutionnelle text,
  contexte_organisationnel text,
  mission_responsabilites text,
  contraintes_budgetaires text,
  enjeux_prioritaires text,
  processus_decision text,
  valeurs_attentes text,
  strategie_approche text,
  recommandations_organisme text,
  CONSTRAINT persona_express_organismes_pkey PRIMARY KEY (project_id),
  CONSTRAINT persona_express_organismes_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT buyer_organismes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pitch (
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  project_id uuid NOT NULL,
  pitch_30_secondes_texte text,
  pitch_30_secondes_appel_action text,
  pitch_court_texte text,
  pitch_court_appel_action text,
  pitch_complet_texte text,
  pitch_complet_appel_action text,
  CONSTRAINT pitch_pkey PRIMARY KEY (project_id),
  CONSTRAINT Pitch_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT Pitch_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  nb_projects text DEFAULT '2'::text,
  drive_folder_url text,
  drive_folder_id text,
  drive_folder_rag text,
  conv_limit text,
  credits_restants text DEFAULT '5'::text,
  credit_limit text DEFAULT '5'::text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.project_collaborators (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text DEFAULT 'read'::text CHECK (role = ANY (ARRAY['read'::text, 'write'::text, 'admin'::text])),
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text])),
  CONSTRAINT project_collaborators_pkey PRIMARY KEY (id),
  CONSTRAINT fk_project_collaborators_invited_by FOREIGN KEY (invited_by) REFERENCES public.profiles(id),
  CONSTRAINT fk_project_collaborators_user_id FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_project_collaborators_project_id FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.project_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  email text NOT NULL,
  role text DEFAULT 'read'::text CHECK (role = ANY (ARRAY['read'::text, 'write'::text, 'admin'::text])),
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  token text NOT NULL UNIQUE,
  used boolean DEFAULT false,
  CONSTRAINT project_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_project_invitations_project_id FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT fk_project_invitations_invited_by FOREIGN KEY (invited_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.project_summary (
  project_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  nom_projet text,
  description_synthetique text,
  produit_service text,
  proposition_valeur text,
  problemes text,
  elements_distinctifs text,
  public_cible text,
  b2c_profile text,
  b2c_problems text,
  b2b_profile text,
  b2b_problems text,
  organismes_profile text,
  organismes_problems text,
  user_id uuid,
  Marche_cible text,
  marches_annexes text,
  project_location text,
  project_type text,
  budget text,
  statut text,
  statut_persona_epxress text,
  statut_mini_swot text,
  Motivation_entrepreneur text,
  statut_success_story text,
  statut_pitch text,
  statut_concurrence text,
  statut_business_model text,
  statut_proposition_valeur text,
  statut_pestel text,
  statut_ressources text,
  drive_folder_url text,
  drive_folder_id text,
  doc_free_id text,
  statut_vision_mission_valeurs text,
  statut_project text,
  equipe_fondatrice text,
  CONSTRAINT project_summary_pkey PRIMARY KEY (project_id),
  CONSTRAINT project_summary_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.form_business_idea(project_id),
  CONSTRAINT project_summary_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.proposition_valeur (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  b2c_profil_aspirations text,
  b2c_profil_besoins text,
  b2c_profil_problemes text,
  b2b_profil_aspirations text,
  b2b_profil_besoins text,
  b2b_profil_problemes text,
  organismes_profil_aspirations text,
  organismes_profil_besoins text,
  organismes_profil_problemes text,
  b2c_carte_valeur_produits_services text,
  b2c_carte_valeur_createurs_benefices text,
  b2c_carte_valeur_solutions text,
  b2b_carte_valeur_produits_services text,
  b2b_carte_valeur_createurs_benefices text,
  b2b_carte_valeur_solutions text,
  organismes_carte_valeur_produits_services text,
  organismes_carte_valeur_createurs_benefices text,
  organismes_carte_valeur_solutions text,
  CONSTRAINT proposition_valeur_pkey PRIMARY KEY (project_id),
  CONSTRAINT proposition_valeur_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT proposition_valeur_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.form_business_idea(project_id),
  CONSTRAINT proposition_valeur_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT proposition_valeur_project_id_fkey1 FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.rag (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  project_id uuid,
  content text,
  metadata jsonb,
  embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rag_pkey PRIMARY KEY (id),
  CONSTRAINT rag_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT rag_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ressources_requises (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ressources_materielles text,
  ressources_humaines text,
  ressources_techniques text,
  CONSTRAINT ressources_requises_pkey PRIMARY KEY (project_id),
  CONSTRAINT ressources_requises_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT ressources_requises_project_id_fkey1 FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.success_story (
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  project_id uuid NOT NULL,
  projections_un_an_titre text,
  projections_un_an_vision text,
  projections_trois_ans_titre text,
  projections_trois_ans_vision text,
  projections_cinq_ans_titre text,
  projections_cinq_ans_vision text,
  message_motivation text,
  CONSTRAINT success_story_pkey PRIMARY KEY (project_id),
  CONSTRAINT success_story_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT success_story_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vision_mission_valeurs (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  vision text,
  mission text,
  valeurs text,
  coherence_strategique text,
  CONSTRAINT vision_mission_valeurs_pkey PRIMARY KEY (project_id),
  CONSTRAINT vision_mission_valeurs_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT vision_mission_valeurs_project_id_fkey1 FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT vision_mission_valeurs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT vision_mission_valeurs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.form_business_idea(project_id)
);