-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.Template (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT Template_pkey PRIMARY KEY (user_id),
  CONSTRAINT Template_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT Template_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.form_business_idea(project_id)
);
CREATE TABLE public.backup_profiles (
  id uuid NOT NULL,
  email text,
  credits_restants text,
  credit_limit text,
  created_at timestamp with time zone,
  CONSTRAINT backup_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT backup_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.backup_project_summary (
  project_id uuid NOT NULL,
  user_id uuid,
  statut_project text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  CONSTRAINT backup_project_summary_pkey PRIMARY KEY (project_id),
  CONSTRAINT backup_project_summary_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT backup_project_summary_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.business_model (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  partenaires_cles text,
  activites_cles text,
  proposition_valeur text,
  ressources_humaines text,
  ressources_financieres text,
  ressources_materielles text,
  ressources_intellectuelles text,
  relations_clients text,
  canaux text,
  segments_clients text,
  structure_couts_analyse text,
  structure_couts_liste_des_couts text,
  flux_revenus_analyse text,
  flux_revenus_liste_des_revenus text,
  CONSTRAINT business_model_pkey PRIMARY KEY (project_id),
  CONSTRAINT business_model_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT business_model_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.concurrence (
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  free_direct_definition text NOT NULL,
  free_direct_importance text,
  free_indirect_definition text,
  free_indirect_importance text,
  free_potentiel_definition text,
  free_potentiel_importance text,
  free_segmentation_concurrentielle text,
  free_critere_differentiation_1 text,
  free_critere_differentiation_2 text,
  free_critere_differentiation_3 text,
  concurrent_1_nom text,
  concurrent_1_description text,
  concurrent_1_url text,
  concurrent_1_forces text,
  concurrent_1_faiblesses text,
  concurrent_1_caracteristiques text,
  concurrent_2_nom text,
  concurrent_2_description text,
  concurrent_2_url text,
  concurrent_2_forces text,
  concurrent_2_faiblesses text,
  concurrent_2_caracteristiques text,
  concurrent_3_nom text,
  concurrent_3_description text,
  concurrent_3_url text,
  concurrent_3_forces text,
  concurrent_3_faiblesses text,
  concurrent_3_caracteristiques text,
  concurrent_4_nom text,
  concurrent_4_description text,
  concurrent_4_url text,
  concurrent_4_forces text,
  concurrent_4_faiblesses text,
  concurrent_4_caracteristiques text,
  concurrent_5_nom text,
  concurrent_5_description text,
  concurrent_5_url text,
  concurrent_5_forces text,
  concurrent_5_faiblesses text,
  concurrent_5_caracteristiques text,
  concurrent_6_nom text,
  concurrent_6_description text,
  concurrent_6_url text,
  concurrent_6_forces text,
  concurrent_6_faiblesses text,
  concurrent_6_caracteristiques text,
  concurrent_7_nom text,
  concurrent_7_description text,
  concurrent_7_url text,
  concurrent_7_forces text,
  concurrent_7_faiblesses text,
  concurrent_7_caracteristiques text,
  concurrent_8_nom text,
  concurrent_8_description text,
  concurrent_8_url text,
  concurrent_8_forces text,
  concurrent_8_faiblesses text,
  concurrent_8_caracteristiques text,
  concurrent_9_nom text,
  concurrent_9_description text,
  concurrent_9_url text,
  concurrent_9_forces text,
  concurrent_9_faiblesses text,
  concurrent_9_caracteristiques text,
  concurrent_10_nom text,
  concurrent_10_description text,
  concurrent_10_url text,
  concurrent_10_forces text,
  concurrent_10_faiblesses text,
  concurrent_10_caracteristiques text,
  avis text,
  recommandations text,
  justification_avis text,
  CONSTRAINT concurrence_pkey PRIMARY KEY (project_id),
  CONSTRAINT concurrence_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT concurrence_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.conversation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  title text NOT NULL DEFAULT 'Nouvelle conversation'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT conversation_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT conversation_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.deliverables (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  project_id uuid,
  entrepreneur_id uuid,
  title text NOT NULL,
  description text,
  type text NOT NULL CHECK (type = ANY (ARRAY['business-model'::text, 'market-analysis'::text, 'pitch'::text, 'legal'::text, 'financial'::text, 'prototype'::text, 'presentation'::text, 'other'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in-progress'::text, 'completed'::text, 'reviewed'::text, 'approved'::text])),
  quality_score integer CHECK (quality_score >= 0 AND quality_score <= 100),
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  file_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deliverables_pkey PRIMARY KEY (id),
  CONSTRAINT deliverables_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT deliverables_entrepreneur_id_fkey FOREIGN KEY (entrepreneur_id) REFERENCES public.profiles(id),
  CONSTRAINT deliverables_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.email_confirmation_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  confirmation_id uuid,
  user_id uuid,
  action text NOT NULL CHECK (action = ANY (ARRAY['sent'::text, 'clicked'::text, 'confirmed'::text, 'failed'::text, 'resent'::text, 'expired'::text, 'cancelled'::text])),
  ip_address inet,
  user_agent text,
  success boolean DEFAULT true,
  error_message text,
  response_time_ms integer,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_confirmation_logs_pkey PRIMARY KEY (id),
  CONSTRAINT email_confirmation_logs_confirmation_id_fkey FOREIGN KEY (confirmation_id) REFERENCES public.email_confirmations(id),
  CONSTRAINT email_confirmation_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.email_confirmations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  email text NOT NULL,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  confirmed_at timestamp with time zone,
  attempts integer DEFAULT 0,
  max_attempts integer DEFAULT 5,
  last_sent_at timestamp with time zone,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'expired'::text, 'failed'::text, 'cancelled'::text])),
  ip_address inet,
  user_agent text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  old_email_confirmed_at timestamp with time zone,
  new_email_confirmed_at timestamp with time zone,
  old_email_token_hash text,
  new_email_token_hash text,
  confirmation_type text DEFAULT 'double'::text CHECK (confirmation_type = ANY (ARRAY['single'::text, 'double'::text])),
  CONSTRAINT email_confirmations_pkey PRIMARY KEY (id),
  CONSTRAINT email_confirmations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  title text NOT NULL,
  description text,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['workshop'::text, 'meeting'::text, 'webinar'::text, 'networking'::text, 'presentation'::text, 'training'::text, 'other'::text])),
  location text,
  organizer_id uuid,
  is_recurring boolean DEFAULT false,
  max_participants integer,
  participants ARRAY DEFAULT '{}'::text[],
  status text DEFAULT 'planned'::text CHECK (status = ANY (ARRAY['planned'::text, 'ongoing'::text, 'completed'::text, 'cancelled'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES public.profiles(id),
  CONSTRAINT events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.form_business_idea (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  nom_projet text,
  produit_service text,
  reponse_besoin text,
  clients_type text,
  moyens_minimum text,
  type_projet text,
  localisation text,
  project_sentence text,
  other_infos text,
  motivations_entrepreneur text,
  equipe_fondatrice text,
  CONSTRAINT form_business_idea_pkey PRIMARY KEY (project_id),
  CONSTRAINT form_business_idea_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.form_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  form_id uuid,
  submitted_by uuid,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'reviewed'::text, 'approved'::text, 'rejected'::text])),
  submitted_at timestamp with time zone DEFAULT now(),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  notes text,
  CONSTRAINT form_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT form_submissions_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.form_templates(id),
  CONSTRAINT form_submissions_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.profiles(id),
  CONSTRAINT form_submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.form_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  title text NOT NULL,
  description text,
  category text NOT NULL CHECK (category = ANY (ARRAY['onboarding'::text, 'feedback'::text, 'evaluation'::text, 'survey'::text, 'application'::text, 'custom'::text])),
  fields jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_by uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT form_templates_pkey PRIMARY KEY (id),
  CONSTRAINT form_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT form_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.invitation_code (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  type text NOT NULL CHECK (type = ANY (ARRAY['super_admin'::text, 'organisation_staff'::text, 'organisation_member'::text])),
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  created_by uuid,
  expires_at timestamp with time zone,
  max_uses integer DEFAULT 1,
  current_uses integer DEFAULT 0,
  is_active boolean DEFAULT true,
  assigned_role text CHECK (assigned_role = ANY (ARRAY['individual'::text, 'member'::text, 'staff'::text, 'organisation'::text, 'super_admin'::text, 'entrepreneur'::text, 'mentor'::text])),
  CONSTRAINT invitation_code_pkey PRIMARY KEY (id),
  CONSTRAINT invitation_code_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT invitation_code_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.juridique (
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  avis text,
  justification_avis text,
  structure jsonb,
  recommandations text,
  CONSTRAINT juridique_pkey PRIMARY KEY (project_id),
  CONSTRAINT juridique_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT juridique_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.marche (
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  free_marche text,
  free_marches_annexe text,
  free_description_du_marche text,
  free_3_enjeux_principaux text,
  free_evolution_du_marche text,
  free_predictions text,
  free_difficulte_a_l_entree text,
  free_details_difficulte_a_l_entree text,
  free_classification text,
  free_justification_concise text,
  free_marche_viable text,
  pay_economique_opportunite_1_description text,
  pay_economique_opportunite_1_source text,
  pay_economique_opportunite_1_url text,
  pay_economique_opportunite_1_impact_potentiel text,
  pay_economique_opportunite_2_description text,
  pay_economique_opportunite_2_source text,
  pay_economique_opportunite_2_url text,
  pay_economique_opportunite_2_impact_potentiel text,
  pay_economique_opportunite_3_description text,
  pay_economique_opportunite_3_source text,
  pay_economique_opportunite_3_url text,
  pay_economique_opportunite_3_impact_potentiel text,
  pay_economique_menace_1_description text,
  pay_economique_menace_1_source text,
  pay_economique_menace_1_url text,
  pay_economique_menace_1_impact_potentiel text,
  pay_economique_menace_2_description text,
  pay_economique_menace_2_source text,
  pay_economique_menace_2_url text,
  pay_economique_menace_2_impact_potentiel text,
  pay_economique_menace_3_description text,
  pay_economique_menace_3_source text,
  pay_economique_menace_3_url text,
  pay_economique_menace_3_impact_potentiel text,
  pay_sociodemographique_opportunite_1_description text,
  pay_sociodemographique_opportunite_1_source text,
  pay_sociodemographique_opportunite_1_url text,
  pay_sociodemographique_opportunite_1_impact_potentiel text,
  pay_sociodemographique_opportunite_2_description text,
  pay_sociodemographique_opportunite_2_source text,
  pay_sociodemographique_opportunite_2_url text,
  pay_sociodemographique_opportunite_2_impact_potentiel text,
  pay_sociodemographique_opportunite_3_description text,
  pay_sociodemographique_opportunite_3_source text,
  pay_sociodemographique_opportunite_3_url text,
  pay_sociodemographique_opportunite_3_impact_potentiel text,
  pay_sociodemographique_menace_1_description text,
  pay_sociodemographique_menace_1_source text,
  pay_sociodemographique_menace_1_url text,
  pay_sociodemographique_menace_1_impact_potentiel text,
  pay_sociodemographique_menace_2_description text,
  pay_sociodemographique_menace_2_source text,
  pay_sociodemographique_menace_2_url text,
  pay_sociodemographique_menace_2_impact_potentiel text,
  pay_sociodemographique_menace_3_description text,
  pay_sociodemographique_menace_3_source text,
  pay_sociodemographique_menace_3_url text,
  pay_sociodemographique_menace_3_impact_potentiel text,
  pay_technologique_opportunite_1_description text,
  pay_technologique_opportunite_1_source text,
  pay_technologique_opportunite_1_url text,
  pay_technologique_opportunite_1_impact_potentiel text,
  pay_technologique_opportunite_2_description text,
  pay_technologique_opportunite_2_source text,
  pay_technologique_opportunite_2_url text,
  pay_technologique_opportunite_2_impact_potentiel text,
  pay_technologique_opportunite_3_description text,
  pay_technologique_opportunite_3_source text,
  pay_technologique_opportunite_3_url text,
  pay_technologique_opportunite_3_impact_potentiel text,
  pay_technologique_menace_1_description text,
  pay_technologique_menace_1_source text,
  pay_technologique_menace_1_url text,
  pay_technologique_menace_1_impact_potentiel text,
  pay_technologique_menace_2_description text,
  pay_technologique_menace_2_source text,
  pay_technologique_menace_2_url text,
  pay_technologique_menace_2_impact_potentiel text,
  pay_technologique_menace_3_description text,
  pay_technologique_menace_3_source text,
  pay_technologique_menace_3_url text,
  pay_technologique_menace_3_impact_potentiel text,
  pay_exploitation_opportunite_1_recommandation text,
  pay_exploitation_opportunite_1_opportunite_associee text,
  pay_exploitation_opportunite_1_priorite text,
  pay_exploitation_opportunite_2_recommandation text,
  pay_exploitation_opportunite_2_opportunite_associee text,
  pay_exploitation_opportunite_2_priorite text,
  pay_exploitation_opportunite_3_recommandation text,
  pay_exploitation_opportunite_3_opportunite_associee text,
  pay_exploitation_opportunite_3_priorite text,
  pay_attenuation_menace_1_recommandation text,
  pay_attenuation_menace_1_menace_associee text,
  pay_attenuation_menace_1_priorite text,
  pay_attenuation_menace_2_recommandation text,
  pay_attenuation_menace_2_menace_associee text,
  pay_attenuation_menace_2_priorite text,
  pay_attenuation_menace_3_recommandation text,
  pay_attenuation_menace_3_menace_associee text,
  pay_attenuation_menace_3_priorite text,
  pay_vue_d_ensemble text,
  pay_synthese_demande text,
  pay_segment_1_nom text,
  pay_segment_1_ca_potentiel text,
  pay_segment_1_taille_volume text,
  pay_segment_1_caracteristiques text,
  pay_segment_1_frequence_achat text,
  pay_segment_1_panier_moyen text,
  pay_ca_an_un text,
  pay_ca_an_deux text,
  pay_ca_an_trois text,
  pay_justification_projections text,
  pay_facteurs_influence text,
  pay_segment_2_nom text,
  pay_segment_2_ca_potentiel text,
  pay_segment_2_taille_volume text,
  pay_segment_2_caracteristiques text,
  pay_segment_2_frequence_achat text,
  pay_segment_2_panier_moyen text,
  pay_segment_3_nom text,
  pay_segment_3_ca_potentiel text,
  pay_segment_3_taille_volume text,
  pay_segment_3_caracteristiques text,
  pay_segment_3_frequence_achat text,
  pay_segment_3_panier_moyen text,
  avis text,
  justification_avis text,
  CONSTRAINT marche_pkey PRIMARY KEY (project_id),
  CONSTRAINT marche_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT marche_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.mentor_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mentor_id uuid,
  entrepreneur_id uuid,
  project_id uuid,
  assigned_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'cancelled'::text])),
  notes text,
  assigned_by uuid,
  assignment_reason text,
  created_by uuid,
  CONSTRAINT mentor_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT mentor_assignments_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.mentors(id),
  CONSTRAINT mentor_assignments_entrepreneur_id_fkey FOREIGN KEY (entrepreneur_id) REFERENCES public.profiles(id),
  CONSTRAINT mentor_assignments_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT mentor_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.profiles(id),
  CONSTRAINT mentor_assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.mentors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  organization_id uuid,
  expertise ARRAY DEFAULT '{}'::text[],
  bio text,
  linkedin_url text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'pending'::text])),
  total_entrepreneurs integer DEFAULT 0,
  success_rate numeric DEFAULT 0,
  rating numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mentors_pkey PRIMARY KEY (id),
  CONSTRAINT mentors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT mentors_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender text NOT NULL CHECK (sender = ANY (ARRAY['user'::text, 'bot'::text])),
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  project_id uuid,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversation(id),
  CONSTRAINT messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT messages_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.mini_swot (
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  project_id uuid NOT NULL,
  economique_opportunite_1 text,
  economique_opportunite_2 text,
  economique_menace_1 text,
  economique_menace_2 text,
  socio_opportunite_1 text,
  socio_opportunite_2 text,
  socio_menace_1 text,
  socio_menace_2 text,
  force_1 text,
  force_2 text,
  force_3 text,
  force_4 text,
  faiblesse_1 text,
  faiblesse_2 text,
  faiblesse_3 text,
  faiblesse_4 text,
  recommandations text,
  avis text,
  justification_avis text,
  CONSTRAINT mini_swot_pkey PRIMARY KEY (project_id),
  CONSTRAINT mini_swot_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT mini_swot_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text CHECK (type = ANY (ARRAY['incubator'::text, 'accelerator'::text, 'venture_capital'::text, 'corporate'::text, 'university'::text, 'government'::text, 'business_school'::text, 'consulting'::text, 'other'::text])),
  domain text UNIQUE,
  logo_url text,
  primary_color text DEFAULT '#F04F6A'::text CHECK (primary_color IS NULL OR primary_color ~ '^#[0-9A-Fa-f]{6}$'::text),
  secondary_color text DEFAULT '#F7774A'::text CHECK (secondary_color IS NULL OR secondary_color ~ '^#[0-9A-Fa-f]{6}$'::text),
  welcome_message text,
  newsletter_enabled boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  logo text,
  website text,
  email text,
  phone text,
  address text,
  updated_at timestamp with time zone DEFAULT now(),
  settings jsonb DEFAULT '{"branding": {"primaryColor": "#ff5932", "secondaryColor": "#1a1a1a"}, "security": {"passwordPolicy": "medium", "sessionTimeout": 480, "twoFactorRequired": false}, "notifications": {"systemAlerts": true, "weeklyReports": false, "projectUpdates": true, "mentorAssignments": true, "emailNotifications": true}}'::jsonb,
  description text,
  founded_year integer,
  mission text,
  vision text,
  values jsonb DEFAULT '[]'::jsonb,
  sectors jsonb DEFAULT '[]'::jsonb,
  stages jsonb DEFAULT '[]'::jsonb,
  geographic_focus jsonb DEFAULT '[]'::jsonb,
  team_size integer,
  specializations jsonb DEFAULT '[]'::jsonb,
  methodology text,
  program_duration_months integer,
  success_criteria text,
  support_types jsonb DEFAULT '[]'::jsonb,
  social_media jsonb DEFAULT '{}'::jsonb,
  is_public boolean DEFAULT true,
  allow_direct_applications boolean DEFAULT true,
  onboarding_completed boolean DEFAULT false,
  onboarding_step integer DEFAULT 0,
  owner_id uuid,
  custom_geographic text,
  custom_type text,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.partners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['investor'::text, 'accelerator'::text, 'incubator'::text, 'corporate'::text, 'government'::text, 'university'::text, 'other'::text])),
  description text,
  logo text,
  website text,
  email text,
  phone text,
  collaboration_type ARRAY DEFAULT '{}'::text[],
  rating integer DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'prospect'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT partners_pkey PRIMARY KEY (id),
  CONSTRAINT partners_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.payment_intents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_intent_id text NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  stripe_payment_intent_id text,
  amount integer,
  currency text DEFAULT 'eur'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT payment_intents_pkey PRIMARY KEY (id),
  CONSTRAINT payment_intents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.persona_express_b2b (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  identite_professionnelle text,
  contexte_organisationnel text,
  responsabilites_cles text,
  enjeux_business text,
  processus_decision text,
  recherche_information text,
  objections_courantes text,
  strategie_approche text,
  recommandations_b2b text,
  CONSTRAINT persona_express_b2b_pkey PRIMARY KEY (project_id),
  CONSTRAINT persona_express_b2b_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT buyer_b2b_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.persona_express_b2c (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  identite text,
  contexte_personnel text,
  motivations_valeurs text,
  defis_frustrations text,
  comportement_achat text,
  presence_digitale text,
  strategies_marketing text,
  approche_vente text,
  avis text,
  recommandations text,
  justification_avis text,
  recommandations_b2c text,
  CONSTRAINT persona_express_b2c_pkey PRIMARY KEY (project_id),
  CONSTRAINT persona_express_b2c_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT buyer_b2c_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.persona_express_organismes (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  identite_institutionnelle text,
  contexte_organisationnel text,
  mission_responsabilites text,
  contraintes_budgetaires text,
  enjeux_prioritaires text,
  processus_decision text,
  valeurs_attentes text,
  strategie_approche text,
  recommandations_organisme text,
  CONSTRAINT persona_express_organismes_pkey PRIMARY KEY (project_id),
  CONSTRAINT buyer_organismes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT persona_express_organismes_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.pitch (
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  project_id uuid NOT NULL,
  pitch_30_secondes_texte text,
  pitch_30_secondes_appel_action text,
  pitch_court_texte text,
  pitch_court_appel_action text,
  pitch_complet_texte text,
  pitch_complet_appel_action text,
  avis text,
  CONSTRAINT pitch_pkey PRIMARY KEY (project_id),
  CONSTRAINT Pitch_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT Pitch_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  nb_projects text DEFAULT '2'::text,
  drive_folder_url text,
  drive_folder_id text,
  drive_folder_rag text,
  conv_limit text,
  abonnement text,
  stripe_customer_id text,
  subscription_status text DEFAULT 'inactive'::text,
  is_member boolean,
  user_role text DEFAULT 'individual'::text CHECK (user_role = ANY (ARRAY['individual'::text, 'member'::text, 'staff'::text, 'organisation'::text, 'super_admin'::text])),
  organization_id uuid,
  invitation_code_used text,
  email_confirmed_at timestamp with time zone,
  email_confirmation_required boolean DEFAULT true,
  first_name text,
  last_name text,
  phone text,
  monthly_credits_remaining integer NOT NULL DEFAULT 50,
  purchased_credits_remaining integer NOT NULL DEFAULT 0,
  monthly_credits_limit integer NOT NULL DEFAULT 50,
  last_credit_reset timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.project_collaborators (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['read'::text, 'write'::text, 'admin'::text])),
  status text NOT NULL DEFAULT 'accepted'::text CHECK (status = ANY (ARRAY['accepted'::text, 'suspended'::text])),
  invited_by uuid NOT NULL,
  invited_at timestamp with time zone NOT NULL DEFAULT now(),
  accepted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT project_collaborators_pkey PRIMARY KEY (id),
  CONSTRAINT project_collaborators_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT project_collaborators_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id),
  CONSTRAINT project_collaborators_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.project_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  email text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['read'::text, 'write'::text, 'admin'::text])),
  invited_by uuid NOT NULL,
  token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  used boolean NOT NULL DEFAULT false,
  invited_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT project_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT project_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id),
  CONSTRAINT project_invitations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.project_summary (
  project_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  nom_projet text,
  description_synthetique text,
  produit_service text,
  proposition_valeur text,
  problemes text,
  elements_distinctifs text,
  public_cible text,
  b2c_profile text,
  b2c_problems text,
  b2b_profile text,
  b2b_problems text,
  organismes_profile text,
  organismes_problems text,
  user_id uuid,
  Marche_cible text,
  marches_annexes text,
  project_location text,
  project_type text,
  budget text,
  statut text,
  statut_persona_express text,
  statut_mini_swot text,
  Motivation_entrepreneur text,
  statut_success_story text,
  statut_pitch text,
  statut_concurrence text,
  statut_business_model text,
  statut_proposition_valeur text,
  statut_pestel text,
  statut_ressources text,
  drive_folder_url text,
  drive_folder_id text,
  doc_free_id text,
  statut_vision_mission_valeurs text,
  statut_project text,
  equipe_fondatrice text,
  date_relance_free_to_premium text,
  statut_relance_free_to_premium text,
  date_paiement date,
  date_mail_avis date,
  statut_juridique text,
  status_action_plan text,
  status_score_viabilite text,
  id uuid,
  CONSTRAINT project_summary_pkey PRIMARY KEY (project_id),
  CONSTRAINT project_summary_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.form_business_idea(project_id),
  CONSTRAINT project_summary_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.proposition_valeur (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  b2c_profil_aspirations text,
  b2c_profil_besoins text,
  b2c_profil_problemes text,
  b2b_profil_aspirations text,
  b2b_profil_besoins text,
  b2b_profil_problemes text,
  organismes_profil_aspirations text,
  organismes_profil_besoins text,
  organismes_profil_problemes text,
  b2c_carte_valeur_produits_services text,
  b2c_carte_valeur_createurs_benefices text,
  b2c_carte_valeur_solutions text,
  b2b_carte_valeur_produits_services text,
  b2b_carte_valeur_createurs_benefices text,
  b2b_carte_valeur_solutions text,
  organismes_carte_valeur_produits_services text,
  organismes_carte_valeur_createurs_benefices text,
  organismes_carte_valeur_solutions text,
  CONSTRAINT proposition_valeur_pkey PRIMARY KEY (project_id),
  CONSTRAINT proposition_valeur_project_id_fkey1 FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT proposition_valeur_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.rag (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  project_id uuid,
  content text,
  metadata jsonb,
  embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rag_pkey PRIMARY KEY (id),
  CONSTRAINT rag_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT rag_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.ressources_requises (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ressources_materielles text,
  ressources_humaines text,
  ressources_techniques text,
  avis text,
  CONSTRAINT ressources_requises_pkey PRIMARY KEY (project_id),
  CONSTRAINT ressources_requises_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT ressources_requises_project_id_fkey1 FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.score_projet (
  project_id uuid NOT NULL,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  analyse_juridique jsonb,
  marche_concurrence jsonb,
  faisabilite_business jsonb,
  innovation_risques jsonb,
  evaluation_finale jsonb,
  score_final integer CHECK (score_final >= 1 AND score_final <= 5),
  CONSTRAINT score_projet_pkey PRIMARY KEY (project_id),
  CONSTRAINT score_projet_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id),
  CONSTRAINT score_projet_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.stripe_customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stripe_customer_id text NOT NULL UNIQUE,
  user_id uuid UNIQUE,
  email text NOT NULL,
  name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stripe_customers_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.stripe_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stripe_subscription_id text NOT NULL UNIQUE,
  stripe_customer_id text NOT NULL,
  user_id uuid,
  product_id text NOT NULL,
  price_id text NOT NULL,
  status text NOT NULL,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stripe_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_subscriptions_stripe_customer_id_fkey FOREIGN KEY (stripe_customer_id) REFERENCES public.stripe_customers(stripe_customer_id),
  CONSTRAINT stripe_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.stripe_webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stripe_event_id text NOT NULL UNIQUE,
  event_type text NOT NULL,
  processed boolean DEFAULT false,
  data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  CONSTRAINT stripe_webhook_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_intents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  project_id uuid,
  stripe_customer_id text,
  product_id text NOT NULL,
  price_id text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  stripe_subscription_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_intents_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_intents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.success_story (
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  project_id uuid NOT NULL,
  projections_un_an_titre text,
  projections_un_an_vision text,
  projections_trois_ans_titre text,
  projections_trois_ans_vision text,
  projections_cinq_ans_titre text,
  projections_cinq_ans_vision text,
  message_motivation text,
  avis text,
  CONSTRAINT success_story_pkey PRIMARY KEY (project_id),
  CONSTRAINT success_story_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT success_story_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);
CREATE TABLE public.vision_mission_valeurs (
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  vision text,
  mission text,
  valeurs text,
  coherence_strategique text,
  avis text,
  CONSTRAINT vision_mission_valeurs_pkey PRIMARY KEY (project_id),
  CONSTRAINT vision_mission_valeurs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.form_business_idea(project_id),
  CONSTRAINT vision_mission_valeurs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT vision_mission_valeurs_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT vision_mission_valeurs_project_id_fkey1 FOREIGN KEY (project_id) REFERENCES public.project_summary(project_id)
);