// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llcliurrrrxnkquwmwsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsY2xpdXJycnJ4bmtxdXdtd3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MDMwOTEsImV4cCI6MjA1MzQ3OTA5MX0.UWfFrlMEQRvRhXYUORmUhrc1A6WLAJbLBnpCWAVaWSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create singleton instance to prevent multiple GoTrueClient instances
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

const getSupabaseClient = () => {
  if (!supabaseInstance) {
    console.log('[Supabase Client] Creating new singleton instance');
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        autoRefreshToken: true,
        persistSession: true,
        storage: window.localStorage,
        detectSessionInUrl: true,
        storageKey: 'sb-llcliurrrrxnkquwmwsi-auth-token',
        flowType: 'pkce',
      }
    });
    console.log('[Supabase Client] Singleton instance created');
  }
  return supabaseInstance;
};

export const supabase = getSupabaseClient();